openapi: 3.0.0
info:
  title: Modello Dati - Scheda P_SIMOG - Scheda di bando di gara SIMOG.
  version: 1.0.0
components:
  schemas:
    AppaltoP_SIMOGType:   
      type: object
      additionalProperties: false
      required: [codiceAppalto,motivoUrgenza,categorieMerceologiche,datiBase,settore]
      properties: 
        codiceAppalto:
          description: Identificativo univoco dell'appalto definito dalla Stazione Appaltante
          type: string
          minLength: 8
          maxLength: 64
        settore: 
          $ref: 'https://raw.githubusercontent.com/anticorruzione-test/npa/appalti/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/SettoreEnum' 
        cigAccordoQuadroConvenzione:
          description: CIG relativo all’accordo quadro/convenzione cui si aderisce
          type: string
        motivoUrgenza:
          $ref: 'https://raw.githubusercontent.com/anticorruzione-test/npa/appalti/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/MotivoUrgenzaEnum'
        motivazioneCIG:
          $ref: 'https://raw.githubusercontent.com/anticorruzione-test/npa/appalti/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/MotivazioneCIGEnum' 
        categorieMerceologiche:
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/anticorruzione-test/npa/appalti/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/CategorieMerceologicheEnum'
        datiBase:
          $ref: 'https://raw.githubusercontent.com/anticorruzione-test/npa/appalti/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseAppaltoType'          
        strumentiSvolgimentoProcedure:
          $ref: 'https://raw.githubusercontent.com/anticorruzione-test/npa/appalti/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/StrumentiSvolgimentoProcedure_SIMOGEnum'
    LottoP_SIMOGType:   
      type: object
      additionalProperties: false
      required: [lotIdentifier,categorieMerceologiche,paritaDiGenereGenerazionale,categoria,datiBase,datiBaseCPV,dataPubblicazione]
      properties:
        lotIdentifier:
          description: Id univoco del lotto generato dalla stazione appaltante
          type: string
        categorieMerceologiche:
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/anticorruzione-test/npa/appalti/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/CategorieMerceologicheEnum'
        afferenteInvestimentiPNRR:
          description: L’appalto o concessione è afferente gli investimenti pubblici finanziati, in tutto o in parte, con le risorse previste dal PNRR (Piano Nazionale di Ripresa e Resilienza) e/o dal PNC (Piano nazionale per gli investimenti complementari)?
          type: boolean    
        acquisizioneCup:
          description: Il contratto è finalizzato alla realizzazione di progetti d'investimento pubblico per i quali è prevista l'acquisizione del codice CUP ai sensi dell'art. 11 L. 3/2003 e ss.mm.? (E' necessario acquisire e comunicare il CUP per interventi finanziati, anche in parte, con risorse Comunitarie) (Si/No)
          type: boolean 
        cupLotto:
          description: Cup associati al lotto
          type: array
          items:
            type: string
            pattern: ^[a-zA-Z0-9]{15}$
        contrattoEsclusoAlleggerito: 
          description: Il contratto è escluso/alleggerito?
          type: boolean
        dataPubblicazione: 
          description: data di pubblicazione
          type: string
          format: datetime
        dataGUCE: 
          description: data GUCE
          type: string
          format: datetime
        dataGURI: 
          description: data GURI
          type: string
          format: datetime
        dataAlboPretorio: 
          description: data albo pretorio
          type: string
          format: datetime
        dataBORE: 
          description: data BORE
          type: string
          format: datetime
        codIstat:
          $ref: 'https://raw.githubusercontent.com/anticorruzione-test/npa/appalti/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/CodIstatEnum' 
        motivoEsclusione:
          $ref: 'https://raw.githubusercontent.com/anticorruzione-test/npa/appalti/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/MotivoEsclusione_SIMOGEnum'
        condizioniNegoziata:
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/anticorruzione-test/npa/appalti/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/CondizioniNegoziata_SIMOGEnum'
        cui:
          description: CUI programma triennale lavori pubblici o programma biennale forniture e servizi
          type: string
          pattern: ^[a-zA-Z0-9]{20,22}$   
        ripetizioniEConsegneComplementari:
          description: L’appalto prevede ripetizioni di servizi/forniture/lavori analoghi e consegne complementari?
          type: boolean
        categoria:
          $ref: 'https://raw.githubusercontent.com/anticorruzione-test/npa/appalti/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/CategoriaEnum' 
        categoriaScorporabile:
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/anticorruzione-test/npa/appalti/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/CategoriaEnum'
        tipologiaLavoro:
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/anticorruzione-test/npa/appalti/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/TipologiaLavoroEnum' 
        docFAP:
          description: è stato realizzato e autorizzato entro i termini lo studio di fattibilità che esenta dall'uso del BIM
          type: boolean        
        ipotesiCollegamento:
          $ref: 'https://raw.githubusercontent.com/anticorruzione-test/npa/appalti/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/IpotesiCollegamentoType'
        paritaDiGenereGenerazionale:
          $ref: 'https://raw.githubusercontent.com/anticorruzione-test/npa/appalti/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/ParitaDiGenereGenerazionaleType' 
        prestazioniComprese:
          $ref: 'https://raw.githubusercontent.com/anticorruzione-test/npa/appalti/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/PrestazioniEnum'       
        quadroEconomicoStandard:
          $ref: 'https://raw.githubusercontent.com/anticorruzione-test/npa/appalti/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/QuadroEconomicoP7Type'
        quadroEconomicoConcessioni:
          $ref: 'https://raw.githubusercontent.com/anticorruzione-test/npa/appalti/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/QuadroEconomicoConcessioniType'
        datiBase:
          $ref: 'https://raw.githubusercontent.com/anticorruzione-test/npa/appalti/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseLottoType' 
        datiBaseContratto:
          $ref: 'https://raw.githubusercontent.com/anticorruzione-test/npa/appalti/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseContrattoType'       
        datiBaseTerminiInvio:
          $ref: 'https://raw.githubusercontent.com/anticorruzione-test/npa/appalti/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiTerminiInvioType'
        datiBaseCPV:
          $ref: 'https://raw.githubusercontent.com/anticorruzione-test/npa/appalti/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseCPVType' 
        datiBaseDocumenti:
          allOf: 
          - $ref: 'https://raw.githubusercontent.com/anticorruzione-test/npa/appalti/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseDocumentiType'  
        datiBaseComunicazione:
          $ref: 'https://raw.githubusercontent.com/anticorruzione-test/npa/appalti/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseComunicazioneType'
        datiBaseDurata:
          $ref: 'https://raw.githubusercontent.com/anticorruzione-test/npa/appalti/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseDurataType'
        datiBaseAggiuntivi:
          $ref: 'https://raw.githubusercontent.com/anticorruzione-test/npa/appalti/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseAggiuntiviType'         
    AnacFormP_SIMOGType:
      description: Contiene tutti i dati necessari per la pubblicazione nazionale.
      allOf: 
      - $ref: 'https://raw.githubusercontent.com/anticorruzione-test/npa/appalti/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/AnacFormBaseType'      
      type: object
      additionalProperties: false
      required: [appalto,lotti]
      properties:      
        appalto:
          $ref: '#/components/schemas/AppaltoP_SIMOGType'
        lotti:
          description: Dati relativi ai lotti
          type: array
          items:
            $ref: '#/components/schemas/LottoP_SIMOGType'          
    SchedaP_SIMOGType:
      description: Bando di gara — SIMOG.
      type: object
      required: [anacForm]
      additionalProperties: false
      properties:
        anacForm:
          $ref: '#/components/schemas/AnacFormP_SIMOGType'         
