openapi: 3.0.0
info:
  title: Modello Dati - Scheda STEV - Scheda di Terminazione Verifiche FVOE (STEV).
  description: | 
    La scheda STEV (Scheda di Terminazione Verifiche FVOE) è una scheda di comunicazione della terminazione delle verifiche FVOE per mancata prosecuzione della procedura di affidamento a seguito di una preliminare consultazione di mercato.\
    La nuova scheda STEV segue una scheda SIM (scheda di Indagine di Mercato) al termine delle verifiche FVOE quando si decide di non proseguire con la procedura di affidamento e va in uno STATO FINALE.\
    La scheda sarà collegata alla precedente scheda SIM tramite il campo ‘ID scheda’.
  version: 1.0.0
components:
  schemas:
    AnacFormSTEVType:
      description: Contiene i dati per la scheda di Terminazione verifiche FVOE.
      type: object
      required: [idScheda,dataChiusuraVerifiche,motivazioneChiusuraVerifiche] 
      additionalProperties: false 
      properties:
        idScheda:
          description: identificativo restituito dal servizio all’invio della scheda SIM.
          type: string   
          format: uuid
          example: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6"      
        dataAvvioVerifiche:
          description: Data di comunicazione dell’elenco delle anagrafiche dei soggetti interessati (SIM)
          type: string
          format: date-time
        dataChiusuraVerifiche:
          description: Data di chiusura del FVOE o della decisione di non proseguire con le verifiche
          type: string
          format: date-time
        motivazioneChiusuraVerifiche:
          $ref: 'https://raw.githubusercontent.com/anticorruzione-test/npa/changelog05/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/MotivoChiusuraVerificheEnum'
    SchedaSTEVType:
      description: Scheda di Terminazione Verifiche FVOE (STEV).
      type: object
      required: [anacForm]
      additionalProperties: false
      properties:
        anacForm:
          $ref: '#/components/schemas/AnacFormSTEVType'