openapi: 3.0.0
info:
  title: Modello Dati - Scheda SIM - Scheda anagrafica per Indagine di Mercato
  description: | 
    La scheda SIM (Scheda anagrafica per indagine di mercato) è una scheda anagrafica che  contiene l’anagrafica dei soggetti che hanno manifestato interesse a seguito di un  eventuale avviso di indagine di mercato che è stato pubblicato utilizzando una scheda PL1 o PL2.
      Oppure può essere inviata con nominativi già a disposizione della SA, senza l'invio preventivo di una PL1 e PL2. \
      Consente di attivare l’FVOE e non attribuisce il CIG.\
      La SIM non porta all'identificazione di alcun OE aggiudicatario.\
      Dopo l’invio di una SIM, è possibile procedere con un affidamento diretto o con la lettera di invito per l’avvio della procedura negoziata.
      Oppure è possibile procedere con una scheda di terminazione qualora i controlli abbiano esito negativo e non si pervenga all'affidamento o si decida di non proseguire nelle procedure di affidamento (STEV - Scheda di terminazione delle verifiche FVOE).
  version: 1.0.0
components:
  schemas:
    AnacFormSIMType:
      description: Anagrafica dei soggetti interessati.
      type: object
      additionalProperties: false
      required: [elencoSoggettiRichiedenti]
      properties:
        elencoSoggettiRichiedenti:
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/anticorruzione-test/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/SoggettoType'
    SchedaSIMType:
      description: Scheda anagrafica per Indagine di Mercato.
      type: object
      required: [anacForm]
      additionalProperties: false
      properties:
        anacForm:
          $ref: '#/components/schemas/AnacFormSIMType'