openapi: 3.0.0
info:
  title: Modello Dati - Scheda I1 - Scheda di inizio prestazione
  version: 1.0.0
components:
  schemas:
    DatiInizioType:
      description: Oggetto che riporta i dati di inizio prestazione
      type: object
      additionalProperties: false
      required: [consegnaSottoRiserva,dataEffettivoInizio,dataFinePrevista]
      properties:
        dataDisposizioneInizio:
          description: Data disposizione dell’inizio della prog. Esecutiva
          allOf:
            - $ref: 'https://raw.githubusercontent.com/anticorruzione-test/npa/datetimeFormat/docs/modello-dati/modello-dati-tipologiche.yaml#/components/schemas/DataOraType'
        dataApprovazione:
          description: Data approvazione del  progetto Esecutivo
          allOf:
            - $ref: 'https://raw.githubusercontent.com/anticorruzione-test/npa/datetimeFormat/docs/modello-dati/modello-dati-tipologiche.yaml#/components/schemas/DataOraType'
        consegnaFrazionata:
          description: Consegna frazionata
          type: boolean
        avvioPerFasi:
          description: L'avvio dell'esecuzione del contratto e' per fasi
          type: boolean
        dataVerbalePrimaConsegna:
          description: Data verbale prima consegna lavori
          allOf:
            - $ref: 'https://raw.githubusercontent.com/anticorruzione-test/npa/datetimeFormat/docs/modello-dati/modello-dati-tipologiche.yaml#/components/schemas/DataOraType'
        dataAvvioPrimaFase:
          description: Data di avvio della prima fase dell'esecuzione del contratto
          allOf:
            - $ref: 'https://raw.githubusercontent.com/anticorruzione-test/npa/datetimeFormat/docs/modello-dati/modello-dati-tipologiche.yaml#/components/schemas/DataOraType'
        dataVerbaleConsegnaDefinitiva:
          description: Data verbale consegna definitiva
          allOf:
            - $ref: 'https://raw.githubusercontent.com/anticorruzione-test/npa/datetimeFormat/docs/modello-dati/modello-dati-tipologiche.yaml#/components/schemas/DataOraType'
        consegnaSottoRiserva:
          description: Consegna sotto riserva di legge?
          type: boolean
        dataEffettivoInizio:
          description: Data di effettivo inizio lavori/servizi/forniture (consegna completa/avvio di tutte le prestazioni del contratto)
          allOf:
            - $ref: 'https://raw.githubusercontent.com/anticorruzione-test/npa/datetimeFormat/docs/modello-dati/modello-dati-tipologiche.yaml#/components/schemas/DataOraType'
        dataFinePrevista:
          description: Data fine prevista per dare ultimazione ai lavori/servizi/forniture 
          allOf:
            - $ref: 'https://raw.githubusercontent.com/anticorruzione-test/npa/datetimeFormat/docs/modello-dati/modello-dati-tipologiche.yaml#/components/schemas/DataOraType'
    AnacFormI1Type:
      description: Contiene tutti i dati di inizio prestazione
      type: object
      additionalProperties: false
      required: [idContratto, datiInizio]
      properties: 
        idContratto:
          description: identificativo del contratto restituito in response alla scheda di Sottoscrizione del contratto.
          type: string   
          format: uuid
          example: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6"      
        datiInizio:
          $ref: '#/components/schemas/DatiInizioType'
    SchedaI1Type:
      description: Avvio dell'esecuzione
      type: object
      required: [anacForm]
      additionalProperties: false
      properties:
        anacForm:
          $ref: '#/components/schemas/AnacFormI1Type'