openapi: 3.0.0
info:
  title: Modello Dati - Scheda ID - Scheda  per l'integrazione dei dati non essenziali ai fini della pubblicità legale e del flusso della procedura.
  description: | 
    In caso di modifica dei cup le operazioni consentite sono:\
    INSERIMENTO: La lista dei CUP attualmente associati al CIG viene completamente sostituita. Viene quindi eliminata la lista esistente e impostata una nuova lista, pari ai valori indicati nel campo CUP della scheda.\
    RIMOZIONE: Viene eliminata la lista esistente. In questo caso il campo CUP NON deve essere valorizzato.\
    \
    La scheda permette la modifica del ribasso di aggiudicazione solo in caso di omessa comunicazione in fase di affidamento.\
    \
    Con questa scheda può essere comunicata anche l'informazione relativa al docFAP, ovvero se è stato realizzato e autorizzato entro i termini lo studio di fattibilità che esenta dall'uso del BIM.\
    \
    La scheda permette infine di modificare l'indirizzo dei documenti di gara    
  version: 1.0.0
components:
  schemas:
    IntegrazioneDatiEsecuzioneType:
      description: Dati inerenti l'inizio dell'esecuzione lavori
      type: object
      required: [dataStipulaContratto,consegnaSottoRiserva,dataEffettivoInizioPrestazione,dataFinePrevistaPrestazione]
      additionalProperties: false
      properties:
        dataStipulaContratto:
          description: Data stipula del contratto
          type: string
          format: date-time 
        consegnaSottoRiserva:
          description: Consegna sotto riserva di legge?
          type: boolean
        dataEffettivoInizioPrestazione:
          description: Data di effettivo inizio lavori/servizi/forniture (consegna completa/avvio di tutte le prestazioni del contratto)
          type: string
          format: date-time
        dataFinePrevistaPrestazione:
          description: Data fine prevista per dare ultimazione ai lavori/servizi/forniture 
          type: string
          format: date-time
    ComunicazioneCUPType:
      description: Dati inerenti la modifica del CUP
      type: object
      required: [operazioneCUP,motivoVariazioneCUP]
      additionalProperties: false
      properties:
        operazioneCUP:
          description: tipo di operazione
          type: string
          enum: ['INSERIMENTO', 'RIMOZIONE'] 
        motivoVariazioneCUP:
            $ref: 'https://raw.githubusercontent.com/anticorruzione-test/npa/chg-07/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/MotivoVariazioneCUPEnum'    
        cup:
          description: Cup
          type: array
          items:
            type: string
            pattern: ^[a-zA-Z0-9]{15}$
    ComunicazioneRibassoAggiudicazioneType:
      description: Dati inerenti la comunicazione del ribasso di aggiudicazione
      type: object
      required: [motivoCorrezione,ribassoAggiudicazione]
      additionalProperties: false
      properties:   
        motivoCorrezione:
            $ref: 'https://raw.githubusercontent.com/anticorruzione-test/npa/chg-07/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/MotivoCorrezioneEnum'    
        ribassoAggiudicazione:
          description: ribasso di aggiudicazione. valori ammessi-> (x<100); sono ammessi valori negativi. I valori positivi saranno considerati come integrazione del campo offertePresentate.offertaEconomica, mentre i valori negativi andranno ad integrare il campo offertePresentate.offertaInAumento.
          type: number
          format: double
          maximum: 100
          exclusiveMaximum: true
    ComunicazioneUrlType:
      description: Dati inerenti la modifica dell'indirizzo dei documenti di gara'
      type: object
      required: [motivoCorrezione,url]
      additionalProperties: false
      properties:
        motivoCorrezione:
            $ref: 'https://raw.githubusercontent.com/anticorruzione-test/npa/chg-07/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/MotivoCorrezioneUrlEnum'    
        url:
          description: Indirizzo dei documenti di gara.
          type: string
          format: url         
    ComunicazioneIDType:
      type: object
      required: [motivoRichiestaModifica]
      additionalProperties: false
      properties:
        motivoRichiestaModifica:
            $ref: 'https://raw.githubusercontent.com/anticorruzione-test/npa/chg-07/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/MotivoRichiestaModificaEnum'    
        comunicazioneCUP:
            $ref: '#/components/schemas/ComunicazioneCUPType'
        comunicazioneRibassoAggiudicazione:
            $ref: '#/components/schemas/ComunicazioneRibassoAggiudicazioneType'
        docFAP:
          description: è stato realizzato e autorizzato entro i termini lo studio di fattibilità che esenta dall'uso del BIM
          type: boolean
        comunicazioneUrl:
            $ref: '#/components/schemas/ComunicazioneUrlType'
        integrazioneDatiEsecuzione:
            $ref: '#/components/schemas/IntegrazioneDatiEsecuzioneType'
    AnacFormIDType:
      type: object
      required: [cig,comunicazione]
      additionalProperties: false
      properties:
        cig:
          description: codice identificativo lotto
          type: string 
        comunicazione:
            $ref: '#/components/schemas/ComunicazioneIDType'    
    SchedaIDType:
      description: Scheda  per l'integrazione dei dati non essenziali ai fini della pubblicità legale e del flusso della procedura.
      type: object
      required: [anacForm]
      additionalProperties: false
      properties:
        anacForm:
          $ref: '#/components/schemas/AnacFormIDType'