openapi: 3.0.0
info:
  title: Modello Dati - Scheda CO1_4 - Scheda di conclusione della procedura.
  version: 1.0.0
components:
  schemas:
    ConclusioneType:
      description: Oggetto che riporta i dati di conclusione finale della procedura.
      type: object
      additionalProperties: false
      required: [dataConclusione]
      properties:
        dataConclusione:
          description: Data conclusione della procedura
          type: string
          format: date-time                    
    AnacFormCO1_4Type:
      description: Contiene tutti i dati di conclusione finale della procedura
      type: object
      additionalProperties: false
      required: [idAppalto,conclusione]
      properties:
        idAppalto:
          description: identificativo del contratto restituito in response alla scheda di creazione della procedura.
          type: string   
          format: uuid
          example: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6" 
        conclusione:
          $ref: '#/components/schemas/ConclusioneType'
    SchedaCO1_4Type:
      description: Scheda di conclusione
      type: object
      required: [anacForm]
      additionalProperties: false
      properties:
        anacForm:
          $ref: '#/components/schemas/AnacFormCO1_4Type'
