openapi: 3.0.0
info:
  title: Modello Dati - Scheda ID - Scheda  per l'integrazione dei dati non essenziali ai fini della pubblicità legale e del flusso della procedura.
  version: 1.0.0
components:
  schemas:
    AnacFormIDType:
      type: object
      required: [cig,motivoRichiestaModifica,cup]
      additionalProperties: false
      properties:
        cig:
          description: codice identificativo lotto
          type: string 
        motivoRichiestaModifica:
            $ref: 'https://raw.githubusercontent.com/anticorruzione-test/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/MotivoRichiestaModificaEnum'    
        cup:
          description: Cup
          type: array
          items:
            type: string
            pattern: ^[a-zA-Z0-9]{15}$
    SchedaIDType:
      description: Scheda  per l'integrazione dei dati non essenziali ai fini della pubblicità legale e del flusso della procedura.
      type: object
      required: [anacForm]
      additionalProperties: false
      properties:
        anacForm:
          $ref: '#/components/schemas/AnacFormIDType'